name: Deploy to Oracle Cloud

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node version
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Download project as artifact
        uses: actions/upload-artifact@master
        with:
          name: bundle
          path: |
            ./build
            ./package.json
            ./package-lock.json
            ./svelte.config.js

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: bundle
          path: ./${{ github.event.repository.name }}

      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: '${{ github.event.repository.name }}'
          TARGET: '~/www/temp'

  post:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd www/temp/${{ github.event.repository.name }}
            # npm ci --prod
            npm install
            rm svelte.config.js package-lock.json
            cd ..
            cp -R ${{ github.event.repository.name }} ~/www                        
            rm -R *
