name: Clone to Oracle Cloud

on:
  push:
    branches: [main]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Execute git clone on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ~/www/temp_builder/${{ github.event.repository.name }}/clone            
            git clone ${{ github.event.repository.clone_url }}
            cd ..
            mv -f clone/${{ github.event.repository.name }}/* .
            npm i
            npm run build
            rm -rf ~/www/${{ github.event.repository.name }}/*
            mv -f build package.json node_modules ~/www/${{ github.event.repository.name }}/
            rm -rf clone/*
            find . \! -name '.env' \! -name 'clone' -delete
